num1 = int(input("enter the first number:"))
num2 = int(input("enter the second number:"))
print("is num1 greater than num2?",num1>num2)
print("is num1 less than num2?",num1<num2)
print("is num1>=num2?",num1>=num2)
print("is num1==num2?",num1==num2)
print("is num1<=num2?",num1<=num2)
print("is num1!=num2?",num1!=num2)