#Take weight (kg) and height (m) as input. Calculate BMI using the formula:BMI = weight / (height ** 2)
weight= int(input("Enter the weight:"))
height = int(input("Enter the height:"))
BMI=weight/(height**2)
print(f"BMI IS {BMI}")