a = int(input("Enter the first number"))
b = int(input("Enter the second number"))
print("Addition",a+b)
print("substraction",a-b)
print("multiplication",a*b)
print("division",a/b)
print("floor division",a//b)
print("modulus",a%b)
print("power",a**b)